### ISSUE TITLE
The render quality in supersplat is much lower than that in the code using gsplat

### ISSUE THREAD

**Issue by qq704554563** [WHU-USI3DV/VistaDream#10]
![supersplat_render](https://github.com/user-attachments/assets/723c4bdd-5dc8-4741-a6ca-200927bd81fa)

**Comment by qq704554563** [comment]
I found that the scales_act function(torch.exp) hasn't been applied to the  scale parameter while saving the ply

**Comment by HpWang-whu** [comment]
Hi @qq704554563 ,
Sorry for the late response as I'm currently going through a very busy month. I checked the ply storage function and corrected some errors. There may still be issues due to simplifications from gsplat, as mentioned in this [issue](https://github.com/playcanvas/supersplat/issues/159). I will try alternative (local) visualization methods to enhance the visualization of the Gaussian field ASAP.

Yours,
